In [1]:
import torch
import numpy as np

In [2]:
x = torch.zeros(3,4)
x.add_(2)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

Gradient Calculation With Autograd

In [3]:
x = torch.rand(4 , requires_grad=True) # if the requires_grad = false , we cant use gradient function
x

tensor([0.1247, 0.0538, 0.8073, 0.0288], requires_grad=True)

In [4]:
y = x + 2
y

tensor([2.1247, 2.0538, 2.8073, 2.0288], grad_fn=<AddBackward0>)

In [5]:
z = y*y*2
z

tensor([ 9.0287,  8.4363, 15.7620,  8.2324], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(10.3649, grad_fn=<MeanBackward0>)

Prediction using Gradient in Numpy


In [4]:
import torch
import numpy as np
x = np.array([1,2,3,4] , dtype = 'float32')
y = np.array([2,4,6,8] , dtype = 'float32')

w = np.array(0.0 , dtype = 'float32')

#prediction
def forward(x):
    return w*x

#loss = MSE
def loss(y , y_predicted):
    return ((y_predicted - y)**2).mean()

#gradient
# MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N 2x (w*x - y)

def gradient(x,y,y_predicted):
    return np.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
epoch = 20

for i in range (epoch):
    y_pred = forward(x)
    l = loss(y , y_pred)
    dw = gradient(x,y,y_pred)

    w -= learning_rate * dw

    print(f'epoch {i+1}: w = {w:.3f} , loss = {l:.3f}')


print(f'Prediction after training: f(5) = {forward(10):.3f}')

    

Prediction before training: f(5) = 0.000
epoch 1: w = 1.200 , loss = 30.000
epoch 2: w = 1.680 , loss = 4.800
epoch 3: w = 1.872 , loss = 0.768
epoch 4: w = 1.949 , loss = 0.123
epoch 5: w = 1.980 , loss = 0.020
epoch 6: w = 1.992 , loss = 0.003
epoch 7: w = 1.997 , loss = 0.001
epoch 8: w = 1.999 , loss = 0.000
epoch 9: w = 1.999 , loss = 0.000
epoch 10: w = 2.000 , loss = 0.000
epoch 11: w = 2.000 , loss = 0.000
epoch 12: w = 2.000 , loss = 0.000
epoch 13: w = 2.000 , loss = 0.000
epoch 14: w = 2.000 , loss = 0.000
epoch 15: w = 2.000 , loss = 0.000
epoch 16: w = 2.000 , loss = 0.000
epoch 17: w = 2.000 , loss = 0.000
epoch 18: w = 2.000 , loss = 0.000
epoch 19: w = 2.000 , loss = 0.000
epoch 20: w = 2.000 , loss = 0.000
Prediction after training: f(5) = 20.000


Prediction using Gradient in Pytorch


In [12]:
import torch
import numpy as np
x = torch.tensor([1,2,3,4] , dtype = torch.float32)
y = torch.tensor([2,4,6,8] , dtype = torch.float32)

w = torch.tensor(0.0 , dtype = torch.float32,requires_grad=True)

#prediction
def forward(x):
    return w*x

#loss = MSE
def loss(y , y_predicted):
    return ((y_predicted - y)**2).mean()

#gradient
# MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N 2x (w*x - y)

def gradient(x,y,y_predicted):
    return torch.dot(2*x, y_predicted-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

#Training
learning_rate = 0.01
epoch = 20

for i in range (epoch):
    y_pred = forward(x)
    l = loss(y , y_pred)
    #dw = gradient(x,y,y_pred)
    l.backward()

    with torch.no_grad():
        dw = w.grad
        w -= learning_rate * dw

    w.grad.zero_()

    print(f'epoch {i+1}: w = {w:.3f} , loss = {l:.3f}')


print(f'Prediction after training: f(5) = {forward(10):.3f}')

    

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300 , loss = 30.000
epoch 2: w = 0.555 , loss = 21.675
epoch 3: w = 0.772 , loss = 15.660
epoch 4: w = 0.956 , loss = 11.314
epoch 5: w = 1.113 , loss = 8.175
epoch 6: w = 1.246 , loss = 5.906
epoch 7: w = 1.359 , loss = 4.267
epoch 8: w = 1.455 , loss = 3.083
epoch 9: w = 1.537 , loss = 2.228
epoch 10: w = 1.606 , loss = 1.609
epoch 11: w = 1.665 , loss = 1.163
epoch 12: w = 1.716 , loss = 0.840
epoch 13: w = 1.758 , loss = 0.607
epoch 14: w = 1.794 , loss = 0.439
epoch 15: w = 1.825 , loss = 0.317
epoch 16: w = 1.851 , loss = 0.229
epoch 17: w = 1.874 , loss = 0.165
epoch 18: w = 1.893 , loss = 0.119
epoch 19: w = 1.909 , loss = 0.086
epoch 20: w = 1.922 , loss = 0.062
Prediction after training: f(5) = 19.225
